services:
  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: ./server
    environment:
      MONGODB_URI: mongodb://mongodb:27017/db_ap
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongodb_data: